---
project_name: bike_detection
output_dir: runs/
model: models/yolo11n.pt

# for a full list of training and augmentation arguments see:
# https://docs.ultralytics.com/modes/train/#train-settings
train_args:
  mode: train
  task: detect
  # yamllint disable-line rule:line-length
  data: ./datasets/esp_camera/geoinformatics_institute/20250523/YOLO/geoinformatics_institute_yolo_dataset.yaml
  epochs: 150
  patience: 70
  save: true
  val: true
  plots: true
  rect: true
  pretrained: true
  cache: true
  verbose: true
  device: mps
  batch: 0.7
  nbs: 32
  multi_scale: true
  workers: 7
  amp: true
  dropout: 0.1
  pose: 0.0
  classes:
    - 0
  # Augmentation Parameters
  hsv_s: 0.7    # hue
  hsv_h: 0.015  # saturation
  hsv_v: 0.5    # brightness
  degrees: 180
  scale: 0.1
  flipud: 0.1
  fliplr: 0.5
  mosaic: 0.0
