---
project_name: bike_aug_custom_loss_preprocessed_dataset
output_dir: runs/
model: models/yolo11n.pt

# for a full list of training and augmentation arguments see:
# https://docs.ultralytics.com/modes/train/#train-settings
train_args:
  mode: train
  task: detect
  # yamllint disable-line rule:line-length
  data: ./datasets/combined_preprocessed/YOLO/combined_preprocessed_yolo_dataset.yaml
  epochs: 300
  patience: 200
  save: true
  val: true
  plots: true
  rect: false
  pretrained: true
  cache: false
  verbose: true
  device: cuda
  batch: 16
  nbs: 16
  multi_scale: true
  workers: 4
  amp: true
  dropout: 0.1
  classes:
    - 0
  # Loss function parameters
  dfl: 2.0
  kobj: 3.0
  box: 5.0
  cls: 0.3
  # Augmentation Parameters
  hsv_s: 0.7    # hue
  hsv_h: 0.015  # saturation
  hsv_v: 0.5    # brightness
  degrees: 180
  scale: 0.1
  flipud: 0.1
  fliplr: 0.5
  mosaic: 0.0
