---
project_name: saddle_detection
output_dir: runs/
model: models/yolo11n.pt

# for a full list of training arguments see:
# https://docs.ultralytics.com/modes/train/#train-settings
train_args:
  task: detect
  mode: train
  data: ../datasets/esp_camera/geoinformatics_institute/some_yaml_file
  epochs: 20
  val: true
  plots: true
  profile: true
  pretrained: true
  cache: true
  classes:
    - 1
