---
project_name: saddle_detection
output_dir: runs/
model: models/yolo11n.pt

# for a full list of training and augmentation arguments see:
# https://docs.ultralytics.com/modes/train/#train-settings
train_args:
  mode: train
  task: detect
  # yamllint disable-line rule:line-length
  data: ./datasets/esp_camera/geoinformatics_institute/20250523/YOLO/geoinformatics_institute_yolo_dataset.yaml
  epochs: 1
  save: true
  val: true
  plots: true
  rect: true
  pretrained: true
  cache: true
  verbose: true
  device: mps
  fraction: 0.2
  batch: 16
  multi_scale: true
  classes:
    - 1
# Augmentation Parameters
