---
project_name: qat_bike_detection
output_dir: runs/
model: models/yolo11n.pt

calib_dataset_path: ./datasets/combined/YOLO
dataset_yaml_file_path: ./datasets/combined/YOLO/combined_yolo_dataset.yaml
input_shape:
  - 3     # C
  - 640   # H
  - 640   # W
onnx_model_path: ./models/onnx/yolo11n.onnx

training_args:
  epochs: 1
  device: 'cpu'
  scheduling: linear
  scheduler_params:
    start_factor: 0.01  # good starting point

quantization_args:
  calib_steps: 12
  num_bits: 8

num_workers: 4
split: 'val'
save_metrics: true
