fail_fast: true

repos:
  # uv lock sync
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.4
    hooks:
      - id: uv-lock
  # secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks